/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLinkIndexRouteImport } from './routes/auth/link/index'
import { Route as ContractContractIdSignRouteImport } from './routes/contract/$contractId.sign'
import { Route as ContractContractIdCompleteRouteImport } from './routes/contract/$contractId.complete'
import { Route as AuthLinkSuccessRouteImport } from './routes/auth/link/success'
import { Route as AuthLinkRobloxRouteImport } from './routes/auth/link/roblox'
import { Route as AuthLinkErrorRouteImport } from './routes/auth/link/error'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkIndexRoute = AuthLinkIndexRouteImport.update({
  id: '/auth/link/',
  path: '/auth/link/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractContractIdSignRoute = ContractContractIdSignRouteImport.update({
  id: '/contract/$contractId/sign',
  path: '/contract/$contractId/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractContractIdCompleteRoute =
  ContractContractIdCompleteRouteImport.update({
    id: '/contract/$contractId/complete',
    path: '/contract/$contractId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLinkSuccessRoute = AuthLinkSuccessRouteImport.update({
  id: '/auth/link/success',
  path: '/auth/link/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkRobloxRoute = AuthLinkRobloxRouteImport.update({
  id: '/auth/link/roblox',
  path: '/auth/link/roblox',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkErrorRoute = AuthLinkErrorRouteImport.update({
  id: '/auth/link/error',
  path: '/auth/link/error',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/user': typeof UserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/link/error': typeof AuthLinkErrorRoute
  '/auth/link/roblox': typeof AuthLinkRobloxRoute
  '/auth/link/success': typeof AuthLinkSuccessRoute
  '/contract/$contractId/complete': typeof ContractContractIdCompleteRoute
  '/contract/$contractId/sign': typeof ContractContractIdSignRoute
  '/auth/link': typeof AuthLinkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/user': typeof UserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/link/error': typeof AuthLinkErrorRoute
  '/auth/link/roblox': typeof AuthLinkRobloxRoute
  '/auth/link/success': typeof AuthLinkSuccessRoute
  '/contract/$contractId/complete': typeof ContractContractIdCompleteRoute
  '/contract/$contractId/sign': typeof ContractContractIdSignRoute
  '/auth/link': typeof AuthLinkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/user': typeof UserRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/link/error': typeof AuthLinkErrorRoute
  '/auth/link/roblox': typeof AuthLinkRobloxRoute
  '/auth/link/success': typeof AuthLinkSuccessRoute
  '/contract/$contractId/complete': typeof ContractContractIdCompleteRoute
  '/contract/$contractId/sign': typeof ContractContractIdSignRoute
  '/auth/link/': typeof AuthLinkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/user'
    | '/auth/callback'
    | '/auth/link/error'
    | '/auth/link/roblox'
    | '/auth/link/success'
    | '/contract/$contractId/complete'
    | '/contract/$contractId/sign'
    | '/auth/link'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/user'
    | '/auth/callback'
    | '/auth/link/error'
    | '/auth/link/roblox'
    | '/auth/link/success'
    | '/contract/$contractId/complete'
    | '/contract/$contractId/sign'
    | '/auth/link'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/user'
    | '/auth/callback'
    | '/auth/link/error'
    | '/auth/link/roblox'
    | '/auth/link/success'
    | '/contract/$contractId/complete'
    | '/contract/$contractId/sign'
    | '/auth/link/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  UserRoute: typeof UserRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLinkErrorRoute: typeof AuthLinkErrorRoute
  AuthLinkRobloxRoute: typeof AuthLinkRobloxRoute
  AuthLinkSuccessRoute: typeof AuthLinkSuccessRoute
  ContractContractIdCompleteRoute: typeof ContractContractIdCompleteRoute
  ContractContractIdSignRoute: typeof ContractContractIdSignRoute
  AuthLinkIndexRoute: typeof AuthLinkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link/': {
      id: '/auth/link/'
      path: '/auth/link'
      fullPath: '/auth/link'
      preLoaderRoute: typeof AuthLinkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/$contractId/sign': {
      id: '/contract/$contractId/sign'
      path: '/contract/$contractId/sign'
      fullPath: '/contract/$contractId/sign'
      preLoaderRoute: typeof ContractContractIdSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/$contractId/complete': {
      id: '/contract/$contractId/complete'
      path: '/contract/$contractId/complete'
      fullPath: '/contract/$contractId/complete'
      preLoaderRoute: typeof ContractContractIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link/success': {
      id: '/auth/link/success'
      path: '/auth/link/success'
      fullPath: '/auth/link/success'
      preLoaderRoute: typeof AuthLinkSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link/roblox': {
      id: '/auth/link/roblox'
      path: '/auth/link/roblox'
      fullPath: '/auth/link/roblox'
      preLoaderRoute: typeof AuthLinkRobloxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link/error': {
      id: '/auth/link/error'
      path: '/auth/link/error'
      fullPath: '/auth/link/error'
      preLoaderRoute: typeof AuthLinkErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  UserRoute: UserRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLinkErrorRoute: AuthLinkErrorRoute,
  AuthLinkRobloxRoute: AuthLinkRobloxRoute,
  AuthLinkSuccessRoute: AuthLinkSuccessRoute,
  ContractContractIdCompleteRoute: ContractContractIdCompleteRoute,
  ContractContractIdSignRoute: ContractContractIdSignRoute,
  AuthLinkIndexRoute: AuthLinkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
