services:
  test-db:
      image: postgres:16.2-alpine
      container_name: bloxtr8
      environment:
        - POSTGRES_DB=bloxtr8-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
      volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      target: base
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env.keys:/app/.env.keys:ro
    working_dir: /app
    command: >
      sh -c "sh ./scripts/env-decrypt-dev.sh &&
             sh ./scripts/env-dev.sh pnpm --filter @bloxtr8/api dev"
    environment:
      - NODE_ENV=development
    restart: "no"

  discord-bot:
    build:
      context: .
      target: base
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env.keys:/app/.env.keys:ro
    working_dir: /app
    command: >
      sh -c "sh ./scripts/env-decrypt-dev.sh &&
             sh ./scripts/env-dev.sh pnpm --filter @bloxtr8/discord-bot dev"
    environment:
      - NODE_ENV=development
    restart: "no"
# Named volumes
volumes:
  pgdata: