services:
  test-db:
    image: postgres:16.2-alpine
    container_name: bloxtr8
    environment:
      - POSTGRES_DB=bloxtr8-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Optimize PostgreSQL for development
    command: postgres -c shared_preload_libraries=pg_stat_statements -c max_connections=100 -c shared_buffers=128MB

  api:
    build:
      context: .
      dockerfile: Dockerfile.base
      target: development
    volumes:
      # Use bind mounts for source code only, not node_modules
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./turbo.json:/app/turbo.json
      - ./.env.keys:/app/.env.keys:ro
      # Use anonymous volume for node_modules to prevent host override
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "sh ./scripts/env-decrypt-dev.sh &&
             pnpm --filter @bloxtr8/api... install --frozen-lockfile --reporter=silent &&
             sh ./scripts/env-dev.sh pnpm --filter @bloxtr8/api dev"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    restart: 'no'
    depends_on:
      - test-db

  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile.base
      target: development
    volumes:
      # Use bind mounts for source code only, not node_modules
      - ./apps/discord-bot:/app/apps/discord-bot
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./turbo.json:/app/turbo.json
      - ./.env.keys:/app/.env.keys:ro
      # Use anonymous volume for node_modules to prevent host override
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "sh ./scripts/env-decrypt-dev.sh &&
             pnpm --filter @bloxtr8/discord-bot... install --frozen-lockfile --reporter=silent &&
             sh ./scripts/env-dev.sh pnpm --filter @bloxtr8/discord-bot dev"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    restart: 'no'
    depends_on:
      - test-db

  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

# Named volumes
volumes:
  pgdata:
  minio_data:
