version: '3.9'

services:
  api:
    build:
      target: base
    env_file:
      - apps/api/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules
    command: pnpm --filter @bloxtr8/api dev
    restart: "no"

  discord-bot:
    build:
      target: base
    env_file:
      - apps/discord-bot/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/discord-bot:/app/apps/discord-bot
      - /app/apps/discord-bot/node_modules
    command: pnpm --filter @bloxtr8/discord-bot dev
    restart: "no"
