version: '3.9'

services:
  api:
    build:
      target: base
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
      - DOTENV_KEY=${API_DOTENV_KEY}
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules
    command: pnpm dev
    restart: "no"

  discord-bot:
    build:
      target: base
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
      - DOTENV_KEY=${BOT_DOTENV_KEY}
    volumes:
      - ./apps/discord-bot:/app/apps/discord-bot
      - /app/apps/discord-bot/node_modules
    command: pnpm dev
    restart: "no"
